"use client";
import { useCallback, useEffect, useState } from "react";
import { DataStatePanel } from "@/components/data-state-panel";
import { StatusMessage } from "@/components/status-message";
import type { ApiEnvelope, ApiFailure } from "@/features/matchday/types";
import { moderationActionRequest, moderationReauthRequest } from "./admin-moderation";
type Report = { reportId:string; roomId:string; roomName:string; roomStatus:string; reporter:string; reason:string; status:string; createdAt:string };
type Audit = { id:string; actor:string|null; action:string; targetType:string; targetId:string; occurredAt:string };
export function AdminModerationView() {
  const [reports,setReports]=useState<Report[]>(); const [audit,setAudit]=useState<Audit[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [r,a]=await Promise.all([fetch("/api/v1/admin/reports",{credentials:"same-origin",cache:"no-store"}),fetch("/api/v1/admin/audit",{credentials:"same-origin",cache:"no-store"})]);const rb=await r.json() as ApiEnvelope<Report[]>&ApiFailure;const ab=await a.json() as ApiEnvelope<Audit[]>&ApiFailure;if(!r.ok||!a.ok)throw new Error(rb.error?.message||ab.error?.message||"无法加载治理数据");setReports(rb.data);setAudit(ab.data);}catch(reason){setError((reason as Error).message||"无法加载治理数据");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function moderate(roomId:string,action:"RESTRICT"|"CLOSE"|"RESTORE"){const password=window.prompt("敏感操作：请输入当前超级管理员密码（验证有效期 5 分钟）");if(!password)return;const reason=window.prompt("请输入本次处理原因（至少 5 字）");if(!reason)return;setBusy(true);setError("");try{const reauth=moderationReauthRequest(password);const proofResponse=await fetch(reauth.url,reauth.init);const proofBody=await proofResponse.json().catch(()=>({})) as ApiFailure;if(!proofResponse.ok)throw new Error(proofBody.error?.message||"管理员密码验证失败");const operation=moderationActionRequest(roomId,action,reason);const response=await fetch(operation.url,operation.init);const body=await response.json().catch(()=>({})) as ApiFailure;if(!response.ok)throw new Error(body.error?.message||"处理失败");await load();}catch(reason){setError((reason as Error).message||"处理失败");}finally{setBusy(false);}}
  if(!reports&&!error)return <DataStatePanel state="loading" title="正在加载举报和审计" description=""/>;if(!reports)return <DataStatePanel state="error" title="治理数据暂不可用" description={error}/>;
  return <div className="space-y-6">{error&&<StatusMessage tone="error" title="操作失败">{error}</StatusMessage>}<section className="surface p-5"><h2 className="display text-2xl font-bold">房间举报</h2>{reports.length===0?<p className="mt-4 text-sm text-[var(--muted)]">暂无举报。</p>:<ul className="mt-4 space-y-4">{reports.map(report=><li key={report.reportId} className="border border-[var(--line)] p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{report.roomName}</strong><span className="text-xs">{report.status} · {report.roomStatus}</span></div><p className="mt-2 text-sm">{report.reason}</p><p className="mt-1 text-xs text-[var(--muted)]">举报人：{report.reporter} · {new Date(report.createdAt).toLocaleString("zh-CN")}</p><div className="mt-3 flex flex-wrap gap-2">{(["RESTRICT","CLOSE","RESTORE"] as const).map(action=><button key={action} disabled={busy} onClick={()=>moderate(report.roomId,action)} className="min-h-10 border border-[var(--ink)] px-3 text-xs font-bold disabled:opacity-50">{action==="RESTRICT"?"限制预测":action==="CLOSE"?"关闭房间":"恢复房间"}</button>)}</div></li>)}</ul>}</section><section className="surface p-5"><h2 className="display text-2xl font-bold">最近审计</h2><ul className="mt-4 divide-y divide-[var(--line)]">{audit.slice(0,50).map(item=><li key={item.id} className="py-3 text-sm"><strong>{item.action}</strong> · {item.targetType}:{item.targetId}<span className="ml-2 text-xs text-[var(--muted)]">{item.actor??"系统"} · {new Date(item.occurredAt).toLocaleString("zh-CN")}</span></li>)}</ul></section></div>;
}
