"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { DataStatePanel } from "@/components/data-state-panel";
import type { ApiEnvelope, ApiFailure } from "@/features/matchday/types";

type Health = "HEALTHY" | "DEGRADED" | "CRITICAL";
type AdminStatus = { generatedAt: string; overall: Health; supplierBudget: { utcDate: string; limit: number; generalUsed: number; settlementUsed: number; settlementReserved: number }; cache: { freshMatches: number; staleMatches: number; unavailableMatches: number; oldestDataAsOf?: string | null }; settlement: { pending: number; failed: number; oldestPendingAt?: string | null; lastSuccessAt?: string | null }; jobs: { queued: number; running: number; failed: number; maxLagSeconds: number } };

export function AdminStatusView() {
  const [status, setStatus] = useState<AdminStatus>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [forbidden, setForbidden] = useState(false); const [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const response = await fetch("/api/v1/admin/status", { credentials: "same-origin", signal: controller.signal, cache: "no-store" }); if (response.status === 401 || response.status === 403) { setForbidden(true); return; } const result = await response.json().catch(() => ({})) as ApiEnvelope<AdminStatus> & ApiFailure; if (!response.ok) throw new Error(result.error?.message || "无法加载系统状态"); setStatus(result.data); } catch (reason) { if ((reason as Error).name !== "AbortError") setError((reason as Error).message || "无法加载系统状态"); } finally { setLoading(false); } })(); return () => controller.abort(); }, [retry]);
  if (loading) return <DataStatePanel state="loading" title="正在检查系统状态" description=""/>;
  if (forbidden) return <DataStatePanel state="forbidden" title="只有超级管理员可以查看" description="此页面仅对两个预置超级管理员开放。系统不会向普通用户或房主返回运营数据。"/>;
  if (error || !status) return <DataStatePanel state="error" title="系统状态暂不可用" description={error || "服务未返回有效状态。"} action={<button onClick={() => { setLoading(true); setError(""); setRetry(value => value + 1); }} className="inline-flex min-h-11 items-center justify-center rounded-full border-2 border-[var(--ink)] px-5 font-bold transition hover:bg-[var(--ink)] hover:text-white">重试</button>}/>;
  const generalRemaining = Math.max(0, status.supplierBudget.limit - status.supplierBudget.settlementReserved - status.supplierBudget.generalUsed);
  return <div><header className="surface flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-xs text-[var(--muted)]">综合状态</p><p className={`mt-1 text-xl font-bold ${tone(status.overall)}`}>{healthLabel(status.overall)}</p></div><time className="tabular text-xs text-[var(--muted)]" dateTime={status.generatedAt}>生成于 {new Date(status.generatedAt).toLocaleString("zh-CN")}</time></header><div className="mt-5 grid gap-4 lg:grid-cols-2"><Panel title="API-FOOTBALL 日额度" status={generalRemaining > 10 ? "HEALTHY" : generalRemaining > 0 ? "DEGRADED" : "CRITICAL"}><Metrics items={[{ label: "普通可用", value: String(generalRemaining) }, { label: "普通已用", value: String(status.supplierBudget.generalUsed) }, { label: "结算已用", value: String(status.supplierBudget.settlementUsed) }, { label: "结算保护", value: String(status.supplierBudget.settlementReserved) }]}/><p className="mt-3 text-xs text-[var(--muted)]">UTC {status.supplierBudget.utcDate} · 总上限 {status.supplierBudget.limit}，普通同步不得侵占结算保护额度。</p></Panel><Panel title="产品缓存" status={status.cache.unavailableMatches ? "CRITICAL" : status.cache.staleMatches ? "DEGRADED" : "HEALTHY"}><Metrics items={[{ label: "新鲜", value: String(status.cache.freshMatches) }, { label: "过期", value: String(status.cache.staleMatches) }, { label: "不可用", value: String(status.cache.unavailableMatches) }]}/></Panel><Panel title="自动结算" status={status.settlement.failed ? "CRITICAL" : status.settlement.pending ? "DEGRADED" : "HEALTHY"}><Metrics items={[{ label: "待处理", value: String(status.settlement.pending) }, { label: "失败", value: String(status.settlement.failed) }, { label: "最近成功", value: status.settlement.lastSuccessAt ? new Date(status.settlement.lastSuccessAt).toLocaleTimeString("zh-CN") : "—" }]}/></Panel><Panel title="后台任务" status={status.jobs.failed ? "CRITICAL" : status.jobs.maxLagSeconds > 300 ? "DEGRADED" : "HEALTHY"}><Metrics items={[{ label: "排队", value: String(status.jobs.queued) }, { label: "运行", value: String(status.jobs.running) }, { label: "失败", value: String(status.jobs.failed) }, { label: "最大延迟", value: `${status.jobs.maxLagSeconds}s` }]}/></Panel></div><p className="mt-5 text-xs leading-5 text-[var(--muted)]">状态页只显示汇总健康信息，不返回 API Key、密码、恢复码、完整会话令牌或未封盘预测选择。</p><div className="mt-5 flex flex-wrap gap-5"><Link href="/admin/users" className="font-bold underline">管理普通用户状态</Link><Link href="/admin/moderation" className="font-bold underline">进入治理收件箱与审计</Link></div></div>;
}
function Panel({ title, status, children }: { title: string; status: Health; children: React.ReactNode }) { return <section className="surface p-5"><header className="flex items-center justify-between gap-3"><h2 className="display text-xl font-bold">{title}</h2><span className={`text-xs font-bold ${tone(status)}`}>{healthLabel(status)}</span></header><div className="mt-5">{children}</div></section>; }
function Metrics({ items }: { items: Array<{ label: string; value: string }> }) { return <dl className="grid grid-cols-2 gap-4 sm:grid-cols-4">{items.map(item => <div key={item.label}><dt className="text-[10px] text-[var(--muted)]">{item.label}</dt><dd className="tabular mt-1 break-all font-bold">{item.value}</dd></div>)}</dl>; }
function tone(status: Health) { return status === "HEALTHY" ? "text-[var(--field)]" : status === "DEGRADED" ? "text-[var(--amber)]" : "text-[var(--coral)]"; }
function healthLabel(status: Health) { return status === "HEALTHY" ? "● 正常" : status === "DEGRADED" ? "▲ 需关注" : "■ 异常"; }
