"use client";
import { useEffect, useState } from "react";
import { Avatar } from "@/components/avatar";
import { DataStatePanel } from "@/components/data-state-panel";
import type { ApiEnvelope, ApiFailure } from "@/features/matchday/types";
import { submissionEventTitle, submissionStatusLabel, submissionSummary, type SubmissionEvent } from "./submission-status-presentation";

type SubmissionStatus = { roomId: string; roomName: string; viewerRole: "room_owner" | "member"; fixtures: SubmissionEvent[] };

export function SubmissionStatusView({ roomId }: { roomId: string }) {
  const [data, setData] = useState<SubmissionStatus>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [forbidden, setForbidden] = useState(false);
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const response = await fetch(`/api/v1/rooms/${encodeURIComponent(roomId)}/submission-status`, { credentials: "same-origin", signal: controller.signal }); if (response.status === 401 || response.status === 403) { setForbidden(true); return; } const result = await response.json().catch(() => ({})) as ApiEnvelope<SubmissionStatus> & ApiFailure; if (!response.ok) throw new Error(result.error?.message || "无法加载提交状态"); if (result.data.viewerRole !== "room_owner") { setForbidden(true); return; } setData(result.data); } catch (reason) { if ((reason as Error).name !== "AbortError") setError((reason as Error).message || "无法加载提交状态"); } finally { setLoading(false); } })(); return () => controller.abort(); }, [roomId]);
  if (loading) return <DataStatePanel state="loading" title="正在加载成员状态" description=""/>;
  if (forbidden) return <DataStatePanel state="forbidden" title="只有房主可以查看" description="成员提交状态仅用于房主确认参与情况；封盘前任何人的选择和投入都不会显示。"/>;
  if (error || !data) return <DataStatePanel state="error" title="提交状态暂不可用" description={error || "服务未返回有效状态。"}/>;
  if (!data.fixtures.length) return <DataStatePanel state="empty" title="暂无目标赛事" description="有可参与的比赛或 F1 场次后，这里会显示成员是否已经提交。"/>;
  return <div><div className="mb-5 rounded-xl border-l-4 border-[var(--field)] bg-[var(--wash-brand-soft)] p-4 text-sm leading-6"><strong>隐私保护已开启</strong><p className="text-[var(--muted)]">这里始终只消费成员名称和是否提交字段，不读取选择、投入或赔率。足球与 F1 场次遵循同一规则。</p></div><div className="space-y-5">{data.fixtures.map(fixture => { const summary = submissionSummary(fixture.members); return <article key={fixture.matchId} className="surface overflow-hidden"><header className="border-b rule p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="display text-xl font-bold">{submissionEventTitle(fixture)}</h2><div className="flex shrink-0 items-center gap-2"><span className={`rounded-full px-2.5 py-0.5 text-xs font-black ${fixture.status === "OPEN" ? "bg-[var(--field)] text-white" : "bg-[var(--wash-neutral)] text-[var(--muted)]"}`}>{submissionStatusLabel(fixture.status)}</span><time className="tabular text-xs text-[var(--muted)]" dateTime={fixture.kickoffAt}>{new Date(fixture.kickoffAt).toLocaleString("zh-CN")}</time></div></div><p className="mt-2 text-xs font-bold text-[var(--field)]">已提交 {summary.submitted} / {summary.total}</p></header><ul className="divide-y divide-[var(--line)]">{fixture.members.map(member => <li key={member.userId} className="flex items-center justify-between gap-4 p-4"><span className="flex min-w-0 items-center gap-3"><Avatar src={member.avatarUrl} version={member.avatarVersion} nickname={member.displayName} size={32}/><span className="truncate font-bold">{member.displayName}</span></span><span className={`shrink-0 text-sm font-bold ${member.submitted ? "text-[var(--field)]" : "text-[var(--muted)]"}`}>{member.submitted ? "✓ 已提交" : "○ 未提交"}</span></li>)}</ul></article>; })}</div></div>;
}
