"use client";
import { useEffect, useState } from "react";
import { MatchCard } from "@/components/match-card";
import { PredictionSlip } from "./prediction-slip";
import { filterMatches, matchAvailability, matchDateKey, summarizeMatches } from "./match-filters";
import { normalizeMatch, type ApiEnvelope, type ApiFailure, type MatchView } from "./types";

export function MatchList({ roomId, interactive = false }: { roomId?: string; interactive?: boolean }) {
  const [matches, setMatches] = useState<MatchView[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [retry, setRetry] = useState(0); const [competition, setCompetition] = useState(""); const [date, setDate] = useState("");
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const query = roomId ? `?roomId=${encodeURIComponent(roomId)}` : ""; const response = await fetch(`/api/v1/matches${query}`, { credentials: "same-origin", signal: controller.signal, cache: "no-store" }); const result = await response.json().catch(() => ({})) as ApiEnvelope<unknown[]> & ApiFailure; if (!response.ok) throw new Error(result.error?.message || "比赛数据暂不可用"); const normalized = Array.isArray(result.data) ? result.data.map(item => normalizeMatch(item as Parameters<typeof normalizeMatch>[0])).filter((item): item is MatchView => item !== null).sort((left, right) => new Date(left.kickoffAt).getTime() - new Date(right.kickoffAt).getTime()) : []; setMatches(normalized); setError(""); } catch (reason) { if ((reason as Error).name !== "AbortError") setError((reason as Error).message || "比赛数据暂不可用"); } finally { setLoading(false); } })(); return () => controller.abort(); }, [roomId, retry]);
  if (loading) return <div aria-live="polite" aria-busy="true" className="space-y-3">{[1,2,3].map(n => <div key={n} className="surface h-36 animate-pulse bg-white/45"/>)}<span className="sr-only">正在加载比赛</span></div>;
  if (error) return <Empty title="暂时无法取得比赛" text={error} action={<button onClick={() => { setLoading(true); setError(""); setRetry(value => value + 1); }} className="border border-[var(--ink)] px-4 py-2 font-bold">重试</button>}/>;
  if (!matches.length) return <Empty title="目前没有可显示的比赛" text="同步完成后，目标赛事会出现在这里。"/>;
  const competitions = [...new Set(matches.map((match) => match.competitionName))].sort((left, right) => left.localeCompare(right, "zh-CN"));
  const dates = [...new Set(matches.map((match) => matchDateKey(match)).filter(Boolean))].sort();
  const visible = filterMatches(matches, { competition, date }); const summary = summarizeMatches(visible);
  const newestDataAsOf = matches.map((match) => match.dataAsOf).filter((value): value is string => Boolean(value)).sort().at(-1);
  return <div><section className="surface mb-5 p-4" aria-label="比赛筛选和数据状态"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-bold">联赛<select value={competition} onChange={(event) => setCompetition(event.target.value)} className="mt-1 min-h-11 w-full border border-[var(--line)] bg-white px-3 text-sm"><option value="">全部联赛（{competitions.length}）</option>{competitions.map((name) => <option key={name} value={name}>{name}</option>)}</select></label><label className="text-xs font-bold">比赛日期<select value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 min-h-11 w-full border border-[var(--line)] bg-white px-3 text-sm"><option value="">全部日期（{dates.length}）</option>{dates.map((value) => <option key={value} value={value}>{new Date(`${value}T00:00:00`).toLocaleDateString("zh-CN", { month: "long", day: "numeric", weekday: "short" })}</option>)}</select></label><button type="button" onClick={() => { setLoading(true); setRetry((value) => value + 1); }} className="min-h-11 self-end border border-[var(--ink)] px-4 text-sm font-bold">刷新数据</button></div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-1 border-t rule pt-3 text-xs text-[var(--muted)]" aria-live="polite"><strong className="text-[var(--ink)]">显示 {summary.total} / {matches.length} 场</strong><span>可预测 {summary.open}</span><span>已结束 {summary.finished}</span><span className={summary.stale ? "text-[var(--amber)]" : ""}>过期 {summary.stale}</span><span className="ml-auto">数据截至 {newestDataAsOf ? new Date(newestDataAsOf).toLocaleString("zh-CN") : "未知"}</span></div></section>{visible.length ? <div className="grid gap-4 xl:grid-cols-2">{visible.map(match => { const predictable = matchAvailability(match).predictable; return <MatchCard key={match.id} match={match} action={interactive && roomId && predictable ? <PredictionSlip roomId={roomId} match={match}/> : undefined}/>; })}</div> : <Empty title="没有符合筛选的比赛" text="请更换联赛或日期筛选条件。" action={<button type="button" onClick={() => { setCompetition(""); setDate(""); }} className="border border-[var(--ink)] px-4 py-2 font-bold">清除筛选</button>}/>}</div>;
}
function Empty({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <section className="surface p-8 text-center"><p className="display text-xl font-bold">{title}</p><p className="mt-2 text-sm text-[var(--muted)]">{text}</p>{action && <div className="mt-5">{action}</div>}</section>; }
