"use client";
import { FormEvent, useEffect, useState } from "react";
import { DataStatePanel } from "@/components/data-state-panel";
import { StatusMessage } from "@/components/status-message";
import type { ApiEnvelope, ApiFailure } from "@/features/matchday/types";

type Profile = { id: string; username: string; nickname: string; roles?: string[] };

export function AccountProfile() {
  const [profile, setProfile] = useState<Profile>(); const [nickname, setNickname] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [logoutPending, setLogoutPending] = useState(false);
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const response = await fetch("/api/v1/account/profile", { credentials: "same-origin", signal: controller.signal }); const result = await response.json().catch(() => ({})) as ApiEnvelope<Profile> & ApiFailure; if (!response.ok) throw new Error(result.error?.message || "无法加载账户资料"); setProfile(result.data); setNickname(result.data.nickname); } catch (reason) { if ((reason as Error).name !== "AbortError") setError((reason as Error).message || "无法加载账户资料"); } finally { setLoading(false); } })(); return () => controller.abort(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSaved(false); try { const response = await fetch("/api/v1/account/profile", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nickname: nickname.trim() }) }); const result = await response.json().catch(() => ({})) as ApiEnvelope<Profile> & ApiFailure; if (!response.ok) throw new Error(result.error?.message || "无法保存昵称"); setProfile(result.data); setNickname(result.data.nickname); setSaved(true); } catch (reason) { setError((reason as Error).message || "无法保存昵称"); } finally { setSaving(false); } }
  async function logout() { setLogoutPending(true); setError(""); try { const response = await fetch("/api/v1/auth/logout", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: "{}" }); if (!response.ok) { const result = await response.json().catch(() => ({})) as ApiFailure; throw new Error(result.error?.message || "退出失败"); } window.location.assign("/login"); } catch (reason) { setError((reason as Error).message || "退出失败"); setLogoutPending(false); } }
  if (loading) return <DataStatePanel state="loading" title="正在加载账户" description=""/>;
  if (!profile) return <DataStatePanel state="error" title="账户资料暂不可用" description={error || "请重新登录后重试。"}/>;
  return <div className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><section className="surface p-5 sm:p-7"><h2 className="display text-2xl font-bold">公开昵称</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">昵称会显示给同一房间的成员，用户名仍用于登录。</p>{error && <div className="mt-4"><StatusMessage tone="error" title="操作失败">{error}</StatusMessage></div>}{saved && <div className="mt-4"><StatusMessage tone="success" title="昵称已更新"/></div>}<form onSubmit={save} className="mt-5"><label htmlFor="nickname" className="mb-2 block text-sm font-bold">昵称</label><input id="nickname" name="nickname" required minLength={2} maxLength={32} value={nickname} onChange={event => setNickname(event.target.value)} className="min-h-12 w-full border border-[var(--line)] bg-white px-3"/><p className="mt-2 text-xs text-[var(--muted)]">2–32 个字符</p><button disabled={saving || nickname.trim() === profile.nickname} className="mt-5 min-h-12 bg-[var(--field)] px-5 font-bold text-white disabled:opacity-45">{saving ? "正在保存…" : "保存昵称"}</button></form></section><aside className="surface p-5 sm:p-7"><h2 className="display text-2xl font-bold">当前会话</h2><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-xs text-[var(--muted)]">用户名</dt><dd className="mt-1 font-bold">{profile.username}</dd></div><div><dt className="text-xs text-[var(--muted)]">账户权限</dt><dd className="mt-1 font-bold">{profile.roles?.includes("super_admin") ? "超级管理员" : "普通用户"}</dd></div></dl><button type="button" onClick={logout} disabled={logoutPending} className="mt-8 min-h-12 w-full border border-[var(--coral)] px-4 font-bold text-[var(--coral)] disabled:opacity-45">{logoutPending ? "正在安全退出…" : "退出当前会话"}</button><p className="mt-3 text-xs leading-5 text-[var(--muted)]">退出只撤销当前浏览器会话，不会删除账户、房间或账本。</p></aside></div>;
}
